name: RDP with Tailscale (Fastest Clean)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Ultra Fast Disk Clean
        run: |
          cmd /c rmdir /s /q "C:\Program Files (x86)\Microsoft Visual Studio"
          cmd /c rmdir /s /q "C:\Program Files\Microsoft Visual Studio"
          cmd /c rmdir /s /q "C:\Program Files\Windows Kits"
          cmd /c rmdir /s /q "C:\Program Files (x86)\Windows Kits"
          cmd /c rmdir /s /q "C:\hostedtoolcache"
          cmd /c rmdir /s /q "C:\ProgramData\chocolatey"
          cmd /c rmdir /s /q "C:\Android"
          cmd /c rmdir /s /q "C:\Program Files\dotnet"
          cmd /c rmdir /s /q "C:\Program Files (x86)\Microsoft SDKs"
          cmd /c rmdir /s /q "C:\Program Files\Microsoft SDKs"
          cmd /c rmdir /s /q "%TEMP%"
          cmd /c rmdir /s /q "C:\Windows\Temp"

      - name: Enable RDP & Disable NLA
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Lsa" -Name "LimitBlankPasswordUse" -Value 0 -Force
          netsh advfirewall firewall add rule name="RDP" dir=in action=allow protocol=TCP localport=3389
          Restart-Service TermService -Force

      - name: Create User
        run: |
          $password = ConvertTo-SecureString "Abc!2024!*1*1*1*" -AsPlainText -Force
          New-LocalUser "RDP" -Password $password -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "RDP"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"

      - name: Install Tailscale
        run: |
          $url = "https://pkgs.tailscale.com/stable/tailscale-setup-1.96.3-amd64.msi"
          $file = "C:\tailscale.msi"
          Invoke-WebRequest $url -OutFile $file
          Start-Process msiexec.exe -ArgumentList "/i $file /quiet /norestart" -Wait
          Remove-Item $file -Force

      - name: Start Tailscale
        run: |
          $ts = "$env:ProgramFiles\Tailscale\tailscale.exe"
          & $ts up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-rdp-$env:GITHUB_RUN_ID
          for ($i=0; $i -lt 15; $i++) {
            Start-Sleep 5
            $ip = & $ts ip -4
            if ($ip) { break }
          }
          echo "RDP_IP=$ip" >> $env:GITHUB_ENV

      - name: Info
        run: |
          Write-Host "IP: $env:RDP_IP"
          Write-Host "User: RDP"
          Write-Host "Pass: Abc!2024!*1*1*1*"
          while ($true) { Start-Sleep 300 }
